feat:solved the first task from the first module
js-tasks-ru/jsbasic-20201214_dronxxx1993 pull request #2
Opened 2020-12-16 19:02 UTC by AndreyIvannikov

2020-12-16 20:27 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Сделать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна делать первый символ заглавным
+ должна работать для пустой строки
```
```diff
Допишите функцию валидации имени пользователя
+ если меньше 4 символов то false
+ если имя корректное, то true
+ если содержит пробелы, то false
```
```diff
Вычислить факториал
+ факториал 3 равен 6 
+ факториал 5 равен 120 
+ факториал 0 равен 1
+ факториал 1 равен 1
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-16 21:15 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Допишите функцию валидации имени пользователя
+ если содержит пробелы, то false
+ если имя корректное, то true
+ если меньше 4 символов то false
```
```diff
Вычислить факториал
+ факториал 0 равен 1
+ факториал 3 равен 6 
+ факториал 1 равен 1
+ факториал 5 равен 120 
```
```diff
Сделать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна делать первый символ заглавным
+ должна работать для пустой строки
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-16 21:32 UTC, SinimaWath requested changes

2020-12-16 21:32 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  let computation = 1;
Хорошо сделал, но есть некоторые замечания по стилю кода:

1) Не хватает отступов между логическими блоками.
2) Название `computation`, не раскрывает, что именно хранится в этой переменной? Какие именно вычисления?

Про стиль можешь почитать тут https://learn.javascript.ru/coding-style

2020-12-16 21:32 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (str.length === 1) {
Ты уверен, что тебе эта проверка нужна?

2020-12-16 21:32 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return `${str[0].toUpperCase()}${str.slice(1)}`
Круто что заюзал шаблонные строки!

2020-12-16 21:33 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return `${str[0].toUpperCase()}${str.slice(1)}`
Потерял `;`

2020-12-16 22:02 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Допишите функцию валидации имени пользователя
+ если содержит пробелы, то false
+ если меньше 4 символов то false
+ если имя корректное, то true
```
```diff
Сделать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна работать для пустой строки
+ должна делать первый символ заглавным
```
```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 5 равен 120 
+ факториал 0 равен 1
+ факториал 3 равен 6 
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-17 14:21 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Сделать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна работать для пустой строки
+ должна делать первый символ заглавным
```
```diff
Допишите функцию валидации имени пользователя
+ если содержит пробелы, то false
+ если имя корректное, то true
+ если меньше 4 символов то false
```
```diff
Вычислить факториал
+ факториал 3 равен 6 
+ факториал 5 равен 120 
+ факториал 1 равен 1
+ факториал 0 равен 1
```
```diff
Проверка на спам
+ должна возвращать true для '1XbeT now'
+ должна возвращать false для 'innocent rabbit'
+ должна возвращать true для 'free xxxxx'
```
```diff
Усечение строки
+ должна не трогать короткую строку 
+ должна усекать строку 
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-17 14:40 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Усечение строки
+ должна усекать строку 
+ должна не трогать короткую строку 
```
```diff
Сделать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна делать первый символ заглавным
+ должна работать для пустой строки
```
```diff
Проверка на спам
+ должна возвращать true для '1XbeT now'
+ должна возвращать true для 'free xxxxx'
+ должна возвращать false для 'innocent rabbit'
```
```diff
Допишите функцию валидации имени пользователя
+ если имя корректное, то true
+ если содержит пробелы, то false
+ если меньше 4 символов то false
```
```diff
Вычислить факториал
+ факториал 3 равен 6 
+ факториал 5 равен 120 
+ факториал 1 равен 1
+ факториал 0 равен 1
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-17 15:03 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Вычислить факториал
+ факториал 3 равен 6 
+ факториал 1 равен 1
+ факториал 0 равен 1
+ факториал 5 равен 120 
```
```diff
Сделать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна делать первый символ заглавным
+ должна работать для пустой строки
```
```diff
Усечение строки
+ должна не трогать короткую строку 
+ должна усекать строку 
```
```diff
Допишите функцию валидации имени пользователя
+ если меньше 4 символов то false
+ если содержит пробелы, то false
+ если имя корректное, то true
```
```diff
Проверка на спам
+ должна возвращать false для 'innocent rabbit'
+ должна возвращать true для '1XbeT now'
+ должна возвращать true для 'free xxxxx'
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-17 20:44 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (str === '') {
Тут можно использовать приведение типов: `!str`

2020-12-17 20:48 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return true;
Тоже стоит добавить отступ.

2020-12-17 20:48 UTC, SinimaWath requested changes
Все ок, кроме некоторых мелочей ;)

2020-12-24 09:13 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Создайте калькулятор
+ должно складывать числа
+ должно умножать числа
```
```diff
Вычислить факториал
+ факториал 5 равен 120 
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 0 равен 1
```
```diff
Допишите функцию валидации имени пользователя
+ если имя корректное, то true
+ если содержит пробелы, то false
+ если меньше 4 символов то false
```
```diff
Сделать первый символ заглавным
+ должна работать для пустой строки
+ должна работать для строки из одной буквы
+ должна делать первый символ заглавным
```
```diff
Проверка на спам
+ должна возвращать false для 'innocent rabbit'
+ должна возвращать true для 'free xxxxx'
+ должна возвращать true для '1XbeT now'
```
```diff
Усечение строки
+ должна усекать строку 
+ должна не трогать короткую строку 
```
```diff
Функция sumSalary(salaries)
+ должна возвращать 0 если нет свойств с зарплатами
+ должна игнорировать специальные числовые значения
+ должна игнорировать свойства других типов
+ должна складывать все зарплаты
```
```diff
Определите, пуст ли объект
+ если у объекта есть хоть одно свойство, то он не пустой
+ {} должен вернуть true
+ объект с удалённым свойством - пустой
+ объект со свойством undefined должен считаться не пустым
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-24 10:04 UTC, SinimaWath approved these changes

2020-12-24 10:05 UTC, merged