feat: resolved 3-module
js-tasks-ru/jsbasic-20201214_dronxxx1993 pull request #3
Opened 2020-12-25 15:48 UTC by AndreyIvannikov

Мне кажется в 5 таске , слишком топорно как то , или нет ?)

2020-12-25 15:56 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```
```diff
Функция showSalary(users, age)
+ для пользователей до 30 лет должна вывести строку с зарплатами
+ для пользователей до 40 лет должна вывести строку с зарплатами
```
```diff
Найти min/max в строке
+ 25,-1,-234,4,   1000
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать 'background-color'
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'list-style-image' 
+ должна оставить пустую строку без изменений 
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-25 16:24 UTC, SinimaWath requested changes

2020-12-25 16:24 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  users.forEach((elem) => {
Давай тут тоже заиспользум деструкторизацию

2020-12-25 16:24 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return str.slice(0, -1);
Не забываем про отступы

2020-12-25 16:24 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  let str = '';
Не забываем, про понятные названия переменных

2020-12-25 16:24 UTC, SinimaWath commented on 3-module/5-task/README.md
> +
Давай это не менять

2020-12-25 16:24 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  });
Функция которую ты передаешь, должна возвращать boolean.

Давай перепишем проще через нашу знакомую проверку: `!!str`

2020-12-25 16:24 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  newStr = newStr.map((item) => +item)
+ - для приведения в Числу, это очень плохой тон, давай переделаем на parseInt, parseFloat или Number

2020-12-25 16:24 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  result.max = newStr[newStr.length - 1];
Давай попробуем использовать функцию Math.min, Math.max

2020-12-26 08:52 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция showSalary(users, age)
+ для пользователей до 40 лет должна вывести строку с зарплатами
+ для пользователей до 30 лет должна вывести строку с зарплатами
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать 'list-style-image' 
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'background-color'
+ должна оставить пустую строку без изменений 
```
```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Найти min/max в строке
+ 25,-1,-234,4,   1000
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-26 17:37 UTC, SinimaWath requested changes

2020-12-26 17:37 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return selectedUsers.slice(0, -1);
Давай перепишем в олну строчку, сразу:
```
return users.
```

И вместо forEach, используй map

2020-12-26 17:37 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  newStr = newStr.map((item) => Number(item))
Это тоже лучше сразу описать, через `. `:
```
newStr = newStr.filter().map()
```

2020-12-27 16:12 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна оставить пустую строку без изменений 
+ должна преобразовать 'list-style-image' 
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'background-color'
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Найти min/max в строке
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
+ 25,-1,-234,4,   1000
```
```diff
Функция showSalary(users, age)
+ для пользователей до 30 лет должна вывести строку с зарплатами
+ для пользователей до 40 лет должна вывести строку с зарплатами
```
```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-27 17:52 UTC, SinimaWath approved these changes

2020-12-27 17:52 UTC, merged