feat: fourth module solved
js-tasks-ru/jsbasic-20201214_dronxxx1993 pull request #4
Opened 2021-01-02 17:05 UTC by AndreyIvannikov

2021-01-02 17:14 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку второй строки в красный
+ должна окрашивать ячейку первой строки в красный
+ должна окрашивать ячейку третьей строки в красный
+ должна окрашивать ячейку пятой строки в красный
+ должна окрашивать ячейку четвёртой строки в красный
```
```diff
Функция makeFriendsList(friends)
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
+ функция должна возвращать HTML список
+ проверяем содержимое списка
```
```diff
Функция highlight
+ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
+ Проставит аттрибут hidden, если  data-available атрибута нет вообще
+ Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
+ Проставит класс male/female, в зависимости от содержимого ячекйки Gender
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2021-01-02 19:53 UTC, SinimaWath requested changes

2021-01-02 19:53 UTC, SinimaWath commented on 4-module/3-task/index.js
> +  }
Давай этот блок выделим в отдельную функциональность, то есть в отдельную функцию, которая будет определять index

2021-01-02 19:53 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    }
Давай разделим на несколько блоков:

1. Для "text-decoration: line-through"
2. Для status.getAttribute('data-available')
3. Для female/male

2021-01-02 19:53 UTC, SinimaWath commented on 4-module/3-task/index.js
> +  let rows = table.tHead.rows[0].cells;
Кажется, это const

2021-01-04 12:09 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку второй строки в красный
+ должна окрашивать ячейку первой строки в красный
+ должна окрашивать ячейку пятой строки в красный
+ должна окрашивать ячейку четвёртой строки в красный
+ должна окрашивать ячейку третьей строки в красный
```
```diff
Функция highlight
+ Проставит класс male/female, в зависимости от содержимого ячекйки Gender
+ Проставит аттрибут hidden, если  data-available атрибута нет вообще
+ Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
+ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
```
```diff
Функция makeFriendsList(friends)
+ проверяем содержимое списка
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
+ функция должна возвращать HTML список
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2021-01-04 17:58 UTC, SinimaWath approved these changes

2021-01-04 17:58 UTC, merged